name: binary tests
on:
  push:
    branches:
      - release/0.0.x
  pull_request:
    branches:
      - release/0.0.x
jobs:
  bin-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install Lair
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: -f --path crates/lair_keystore

      - name: Run Bin Tests
        uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: 1
        with:
          command: test
          args: --manifest-path crates/lair_keystore_client/Cargo.toml --features=bin-tests
