name: static analysis
on:
  push:
    branches:
      - v0.0.x
  pull_request:
    branches:
      - v0.0.x
jobs:
  static-analysis:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Cargo Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
