name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
          "1.77.2", # Check the version used by Holochain
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: Install vcpkg packages
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          triplet: x64-windows-release
          token: ${{ github.token }}
          manifest-dir: ${{ github.workspace }}/.github/manifest
          github-binarycache: true

      - name: Set vcpkg env
        shell: bash
        if: matrix.os == 'windows-latest'
        run: echo "SODIUM_LIB_DIR=\"$HOME\\vcpkg\\packages\\libsodium_x64-windows-release\\lib\"" >> "$GITHUB_ENV"

      - name: Install lair-keystore-0.4.4 for fwd compat test
        shell: bash
        run: |
          cargo install lair_keystore@0.4.4 --debug
          mv $(which lair-keystore){,-0.4.4}

      - name: Make Test
        if: matrix.os != 'windows-latest'
        run: make test
